/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivateIndexRouteImport } from './routes/private/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as AnotherIndexRouteImport } from './routes/another/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as PostsIdRouteImport } from './routes/posts/$id'
import { Route as CustomersCreateRouteImport } from './routes/customers/create'
import { Route as CustomersIdRouteImport } from './routes/customers/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/private/',
  path: '/private/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotherIndexRoute = AnotherIndexRouteImport.update({
  id: '/another/',
  path: '/another/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCreateRoute = CustomersCreateRouteImport.update({
  id: '/customers/create',
  path: '/customers/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/create': typeof CustomersCreateRoute
  '/posts/$id': typeof PostsIdRoute
  '/about/': typeof AboutIndexRoute
  '/another/': typeof AnotherIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/private/': typeof PrivateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/create': typeof CustomersCreateRoute
  '/posts/$id': typeof PostsIdRoute
  '/about': typeof AboutIndexRoute
  '/another': typeof AnotherIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/posts': typeof PostsIndexRoute
  '/private': typeof PrivateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/create': typeof CustomersCreateRoute
  '/posts/$id': typeof PostsIdRoute
  '/about/': typeof AboutIndexRoute
  '/another/': typeof AnotherIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/private/': typeof PrivateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers/$id'
    | '/customers/create'
    | '/posts/$id'
    | '/about/'
    | '/another/'
    | '/customers/'
    | '/posts/'
    | '/private/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers/$id'
    | '/customers/create'
    | '/posts/$id'
    | '/about'
    | '/another'
    | '/customers'
    | '/posts'
    | '/private'
  id:
    | '__root__'
    | '/'
    | '/customers/$id'
    | '/customers/create'
    | '/posts/$id'
    | '/about/'
    | '/another/'
    | '/customers/'
    | '/posts/'
    | '/private/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersCreateRoute: typeof CustomersCreateRoute
  PostsIdRoute: typeof PostsIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AnotherIndexRoute: typeof AnotherIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/': {
      id: '/private/'
      path: '/private'
      fullPath: '/private/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/another/': {
      id: '/another/'
      path: '/another'
      fullPath: '/another/'
      preLoaderRoute: typeof AnotherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/create': {
      id: '/customers/create'
      path: '/customers/create'
      fullPath: '/customers/create'
      preLoaderRoute: typeof CustomersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersIdRoute: CustomersIdRoute,
  CustomersCreateRoute: CustomersCreateRoute,
  PostsIdRoute: PostsIdRoute,
  AboutIndexRoute: AboutIndexRoute,
  AnotherIndexRoute: AnotherIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  PrivateIndexRoute: PrivateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
